# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  MajorVersion: 0
  MinorVersion: 1
  PatchVersion: 0

pr:
  branches:
    exclude:
    - master
    - release/*

name: $(MajorVersion).$(MinorVersion).$(PatchVersion).$(Rev:r)

jobs:
 - job: nonprod
   pool:
     vmImage: 'Ubuntu 18.04'
   variables:
   - group: 'azure_service_connection'
   steps:
   # Install python
   - task: UsePythonVersion@0
     inputs:
       versionSpec: 3.5
       architecture: 'x64'
   - script: |
       python -m pip install --upgrade pip setuptools wheel
       export ENVIRONMENT=nonprod
     displayName: 'Install python'
