# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  MajorVersion: 0
  MinorVersion: 1
  PatchVersion: 0

pr:
  branches:
    exclude:
    - master
    - release/*

name: $(MajorVersion).$(MinorVersion).$(PatchVersion).$(Rev:r)

jobs:
 - job: nonprod
   pool:
     vmImage: 'Ubuntu 18.04'
   variables:
   - group: 'azure_service_connection'
   - group: 'aws_service_connection'
   steps:
   # Install python
   - task: UsePythonVersion@0
     inputs:
       versionSpec: 3.5
       architecture: 'x64'
   - script: |
       python -m pip install --upgrade pip setuptools wheel
       export ENVIRONMENT=nonprod
     displayName: 'Install python'
   - task: AzureCLI@2
     displayName: 'azure install'
     inputs:
       azureSubscription: 'Free Trial (4c1fcf71-64f7-4bc1-8f8e-211c1c5258e4)'
       scriptLocation: 'inlineScript'
       inlineScript: |
         export ENVIRONMENT=nonprod
   # AWS Toolkit for Azure DevOps should be installed in organization
   # https://marketplace.visualstudio.com/acquisition?itemName=AmazonWebServices.aws-vsts-tools
   # AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
   - task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
     displayName: 'Terraform Validate'
     inputs:
       scriptType: 'bash'
       scriptLocation: 'inlineScript'
       inlineScript: |
         export ENVIRONMENT=nonprod
         make install_terraform_linux
         make install_JQ_linux
         make terraform_validate
       useGlobalConfig: true
       workingDirectory: '$(System.DefaultWorkingDirectory)'
   - task: PublishBuildArtifacts@1
     displayName: 'Publish Artifact: azurekv-nonprod'
     inputs:
       ArtifactName: 'azurekv-nonprod'
       PathtoPublish: '$(Build.SourcesDirectory)'
